[package]
name = "discord-c2"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.0", features = ["full"] }
async-process = "1.7.0"
dotenv = "0.15.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
public-ip-addr = "0.1"
anyhow = "1.0.70"
tempfile = "3.5.0"
uuid = { version = "1.3.2", features = ["v4"] }
zip = "0.6.4"
reqwest = "0.11.17"
winapi = "0.3.9"
chrono = "0.4.24"

[dependencies.serenity]
default-features = false
features = ["client", "gateway", "rustls_backend", "model"]
version = "0.11.5"

[profile.release]
opt-level = "s"
debug = 0
strip = "debuginfo"
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
codegen-units = 256
