[package]
name = "discord_c2"
version = "0.2.5"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = {version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "collector", "framework", "standard_framework"] }
tokio = { version = "1.21.2", features = ["full"] }
uuid = { version = "0.8", features = ["v4"] }
tracing = "0.1.23"
tracing-subscriber = "0.3.16"
sysinfo = "0.28.3"
whoami = "1.4.0"
reqwest = "0.11.14"
anyhow = "1.0.70"
chrono = "0.4"
parking_lot = "0.12.1"

[profile.release]
opt-level = "z"
strip = "symbols"
codegen-units = 50
lto = "fat"
