[package]
name = "discord_c2"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = {version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "collector"] }
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
uuid = { version = "0.8", features = ["v4"] }
tracing = "0.1.23"
tracing-subscriber = "0.3.16"
sysinfo = "0.28.3"
whoami = "1.4.0"
reqwest = "0.11.14"
anyhow = "1.0.70"

[profile.release]
opt-level = "z"
strip = "symbols"
codegen-units = 50
lto = "fat"
