[package]
name = "discordbot"
version = "0.1.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = {version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "collector", "framework", "standard_framework"] }
tokio = { version = "1.21.2", features = ["full"] }
uuid = { version = "1.3.0", features = ["v4"] }
sysinfo = "0.28.3"
whoami = "1.4.0"
reqwest = "0.11.14"
anyhow = "1.0.70"
chrono = "0.4"
litcrypt = "0.3.0"
goldberg = "0.1.0"
is_executable = "1.0.1"

[profile.release]
opt-level = "z"
strip = "symbols"
codegen-units = 50
lto = "fat"
